### ISSUE TITLE
 The content of QVdata and dQdvdata data

### ISSUE THREAD

**Issue by Yufeifeik** [artdreamer/Battery-Early-Capacity-Trajectory-Prediction#1]
Can you explain QVdata and dQdvdata header?IThere are many columns of data, and I don't understand what they mean. They are located at dataset/48NMC.

**Comment by artdreamer** [comment]
Thanks for your comments. The repository has just been created, and the documents are still in preparation. I just created a readme file for the folder `./dataset/48 NMC` to explain your question.

**Comment by Yufeifeik** [comment]
Thank you for your detailed answers.
